workflows:
  android_build:
    name: Build Android APK
    instance_type: linux
    environment:
      node: 18
      npm: 9
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: expo build:android -t apk
    artifacts:
      - android/app/build/outputs/**/*.apk
