workflows:
  android_build:
    name: Build React Native Android (Debug APK)
    instance_type: linux
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Construir APK
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
