workflows:
  react_native_expo:
    name: Build Expo (Android APK)
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      node: latest
      npm: latest
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Build APK con Expo
        script: |
          npx expo install
          npx expo export
          npx expo prebuild
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
