name: Android Debug APK (Expo prebuild)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Use Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Expo prebuild (Android)
        env:
          EXPO_NO_TELEMETRY: '1'
          CI: 'true'
        run: npx expo prebuild -p android --clean

      - name: Make gradlew executable
        run: cd android && chmod +x gradlew

      - name: Patch settings.gradle
        run: |
          cd android
          cat > settings.gradle <<'EOF'
          pluginManagement {
              repositories {
                  gradlePluginPortal()
                  google()
                  mavenCentral()
              }
              plugins {
                  id 'com.android.application' version '8.1.0'
                  id 'com.android.library' version '8.1.0'
                  id 'org.jetbrains.kotlin.android' version '1.8.22'
              }
          }

          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }

          rootProject.name = "android"
          include(":app")
          EOF

      - name: Build APK (debug)
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
